//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jukebox_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlaylist
    {
        public int PlaylistID { get; set; }
        public string SongTitle { get; set; }
        public Nullable<int> Score { get; set; }
        public string Path { get; set; }
    }
}
